name: login
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-81.0.dev <4.0.0'

dependencies:
  cloud_firestore: ^4.6.0
  firebase_auth: ^4.5.0
  firebase_core: ^2.11.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
