// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVwgs6uOnfks70-fuLQRw0aF2wSd6KJfs',
    appId: '1:295532290783:web:4c516a28cde5d75f66bf6a',
    messagingSenderId: '295532290783',
    projectId: 'flutter-5788c',
    authDomain: 'flutter-5788c.firebaseapp.com',
    databaseURL: 'https://flutter-5788c-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-5788c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbQZnV1rrsVL41PptgxGMEoV-5h0PujPY',
    appId: '1:295532290783:android:7f8db7cc360412cb66bf6a',
    messagingSenderId: '295532290783',
    projectId: 'flutter-5788c',
    databaseURL: 'https://flutter-5788c-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-5788c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCONj6AhBB1o1g3VGzcQLUiHqSmWqFhY1Q',
    appId: '1:295532290783:ios:825eada29bcb880766bf6a',
    messagingSenderId: '295532290783',
    projectId: 'flutter-5788c',
    databaseURL: 'https://flutter-5788c-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-5788c.appspot.com',
    iosClientId: '295532290783-jen7treakocffn5717laqs9t5l400mtq.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCONj6AhBB1o1g3VGzcQLUiHqSmWqFhY1Q',
    appId: '1:295532290783:ios:29c3e6720e05dc7b66bf6a',
    messagingSenderId: '295532290783',
    projectId: 'flutter-5788c',
    databaseURL: 'https://flutter-5788c-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-5788c.appspot.com',
    iosClientId: '295532290783-9b0ra457nmtqcdp1t100a3643l6foo8g.apps.googleusercontent.com',
    iosBundleId: 'com.example.login.RunnerTests',
  );
}
