// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcSpHQb0LnTtrC9JKTuZC8XRqcOWQonuY',
    appId: '1:462304959449:web:9372ce2b097c9690a817c8',
    messagingSenderId: '462304959449',
    projectId: 'banquillosl',
    authDomain: 'banquillosl.firebaseapp.com',
    storageBucket: 'banquillosl.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0YgLtEC12omFR9QE93sHbekJpZi_X0fg',
    appId: '1:462304959449:android:451e4751f61c9076a817c8',
    messagingSenderId: '462304959449',
    projectId: 'banquillosl',
    storageBucket: 'banquillosl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9vhzKYdFqF26QfNxrmH6Ci9kV47Nj7TQ',
    appId: '1:462304959449:ios:24aafc1ed1775116a817c8',
    messagingSenderId: '462304959449',
    projectId: 'banquillosl',
    storageBucket: 'banquillosl.appspot.com',
    iosClientId: '462304959449-omst8rdoekoppb6o18jufbs9fplpqlfj.apps.googleusercontent.com',
    iosBundleId: 'com.example.banquillosl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9vhzKYdFqF26QfNxrmH6Ci9kV47Nj7TQ',
    appId: '1:462304959449:ios:8c05261a0f23121ea817c8',
    messagingSenderId: '462304959449',
    projectId: 'banquillosl',
    storageBucket: 'banquillosl.appspot.com',
    iosClientId: '462304959449-q2dftjoeu8cqqmtm1qmt9i3lburl51cu.apps.googleusercontent.com',
    iosBundleId: 'com.example.banquillosl.RunnerTests',
  );
}
